// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPdeRnYd7JFTaqBW0Fsmz-i7kwNvGYcbQ',
    appId: '1:861643519791:web:41fd47116b9fb8655653da',
    messagingSenderId: '861643519791',
    projectId: 'fruit-hub-ad64a',
    authDomain: 'fruit-hub-ad64a.firebaseapp.com',
    storageBucket: 'fruit-hub-ad64a.firebasestorage.app',
    measurementId: 'G-2WC4PX5GCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW1IiSINZhEKn6HBtxiwDC0P4PkuiDk34',
    appId: '1:861643519791:android:871bc05a645f462e5653da',
    messagingSenderId: '861643519791',
    projectId: 'fruit-hub-ad64a',
    storageBucket: 'fruit-hub-ad64a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTk0v7ALYQWph7uhLcHfJHqTvGppLtWpQ',
    appId: '1:861643519791:ios:a6ff5c34fb240fe55653da',
    messagingSenderId: '861643519791',
    projectId: 'fruit-hub-ad64a',
    storageBucket: 'fruit-hub-ad64a.firebasestorage.app',
    androidClientId: '861643519791-nqejhegrd3t70fp5qs2qiieqqtsf3bj9.apps.googleusercontent.com',
    iosClientId: '861643519791-klm5tb7mp72348pjgb2ao5gu2670e7u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitAppDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTk0v7ALYQWph7uhLcHfJHqTvGppLtWpQ',
    appId: '1:861643519791:ios:77cf261b339406b25653da',
    messagingSenderId: '861643519791',
    projectId: 'fruit-hub-ad64a',
    storageBucket: 'fruit-hub-ad64a.firebasestorage.app',
    androidClientId: '861643519791-nqejhegrd3t70fp5qs2qiieqqtsf3bj9.apps.googleusercontent.com',
    iosClientId: '861643519791-ncvppk3stbjlrk99obj7oji7efjpj9rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitAppDashboard.RunnerTests',
  );
}
